### ISSUE TITLE
Bug on El5 - Cant write files to tmp dir

### ISSUE THREAD

**Issue by oswalpalash** [bluehost/wp-tools#11]
Error Message : Too many concurrent executions; try again later. at /home/wpupgrade/wp-tools line 571.

Strace : 
chdir("/home/wpupgrade")                = 0
open("/tmp/wp_backup-0001.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/usr/share/locale/locale.alias", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=2528, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f1cb322a000
read(3, "# Locale name alias data base.\n#"..., 4096) = 2528
read(3, "", 4096)                       = 0
close(3)                                = 0
munmap(0x7f1cb322a000, 4096)            = 0
open("/usr/share/locale/en_IN/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/tmp/wp_backup-0002.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0003.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0004.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0005.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0006.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0007.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0008.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0009.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0010.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0011.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0012.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0013.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0014.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0015.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0016.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)
open("/tmp/wp_backup-0017.pid", O_RDWR|O_CREAT, 0666) = -1 EACCES (Permission denied)

**Comment by c2pAYmx1ZWhvc3QuY29t** [comment]
@oswalpalash 

What version (commit) of the tool are you using?

Can you also provide some context as to your usage pattern?

**Comment by oswalpalash** [comment]
Using the latest git pull (version 1.02). 
We're trying to upgrade installations of wordpress which are lesser than version  3.x
@c2pAYmx1ZWhvc3QuY29t

**Comment by chazmcgarvey** [comment]
I am closing this issue in preparation for archiving.
