### ISSUE TITLE
Tar Bug on EL5 - Cant create a tarball for backup

### ISSUE THREAD

**Issue by oswalpalash** [bluehost/wp-tools#12]
Error Message : 
tar: unrecognized option `--transform=s/^wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.MANIFEST$/wp_backup.MANIFEST/'
Try `tar --help' or `tar --usage' for more information.
Unable to backup: Failed to create backup file at /home/wpupgrade/wp-tools line 777.

Strace :
stat("public_html/wordpress/wp-config.php.backup", 0x12da140) = -1 ENOENT (No such file or directory)
stat("wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.temporary.my.cnf", {st_mode=S_IFREG|0600, st_size=45, ...}) = 0
unlink("wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.temporary.my.cnf") = 0
stat("wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.sql", {st_mode=S_IFREG|0644, st_size=203674, ...}) = 0
unlink("wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.sql") = 0
stat("wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.temporary.my.cnf", 0x12da140) = -1 ENOENT (No such file or directory)
stat("wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.sql", 0x12da140) = -1 ENOENT (No such file or directory)
stat("wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.MANIFEST", {st_mode=S_IFREG|0644, st_size=53, ...}) = 0
unlink("wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.MANIFEST") = 0
stat("wp_backupdbf4ec15ced25792c5e5a0524a3d5ccd.temporary.my.cnf", 0x12da140) = -1 ENOENT (No such file or directory)
close(4)                                = 0
unlink(".wp_backup-dbf4ec15ced25792c5e5a0524a3d5ccd.pid") = 0
close(3)                                = 0
unlink("tmp/wp_backup-0001.pid")        = 0
exit_group(1)                           = ?

**Comment by chazmcgarvey** [comment]
I am closing this issue in preparation for archiving.
