### ISSUE TITLE
Suggested method for installation on cPanel/WHM CentOS 6.7 Servers

### ISSUE THREAD

**Issue by brianjking** [bluehost/wp-tools#2]
Is there an installation method that you suggest using specifically for servers running cPanel/WHM on CentOS 6.7 x86_64?

Thanks!

**Comment by chazmcgarvey** [comment]
Two ideas, depending on your preference and needs:

CPAN method:

```
cpanm --sudo App::WordPressTools
# or
cpanm --sudo https://github.com/bluehost/wp-tools/archive/dist-1.0.tar.gz
```

Perhaps build an RPM:

```
# something like this:
cpantorpm --install-type site App::WordPressTools
```

I haven't used the RPM method and am not sure how complete the generated RPMs from `cpantorpm` are, but it may be useful in cases where RPMs are easier to deal with than CPAN.

Just FYI: I'm also working on a fat-packed version (for curl/wget installation), mostly meant for those interested in getting started quickly without having to install cpanm or mess around with Perl modules.

**Comment by brianjking** [comment]
@chazmcgarvey 

Using CentOS 6.7 on a Liquidweb server I'm seeing this error when attempting to install. Suggestions?

`[root@lw ~]# cpanm --sudo https://github.com/bluehost/wp-tools/archive/dist-1.0.tar.gz
-bash: cpanm: command not found
[root@lw ~]#
`

**Comment by chazmcgarvey** [comment]
To solve that, you'll need to install `cpanm` (see https://github.com/miyagawa/cpanminus#installation).

Alternatively, you can actually use any CPAN client, like `cpan` (which you are likely to already have installed on your system). The tricky bit is that `cpan` usually needs to be configured before it can really be used, and many people find that process confusing. But it is an option.

If you don't have `cpanm` and you're unfamiliar with installing software using the normal CPAN module, I would actually recommend you just follow the instructions for downloading just the executable (https://github.com/bluehost/wp-tools#downloading-just-the-executable), and then optionally copy the file to `/usr/local/bin/` if you need it in a system directory.

**Comment by chazmcgarvey** [comment]
I am closing this issue in preparation for archiving.
