### ISSUE TITLE
WordPress's .maintenance file will be changing

### ISSUE THREAD

**Issue by voldemortensen** [bluehost/wp-tools#6]
In WordPress 4.5, the .maintenance file will likely be changed. The issue can be found here: https://core.trac.wordpress.org/ticket/35066

This will effect our checks and will need to update accordingly.

Code for reference:
https://github.com/bluehost/wp-tools/blob/master/script/wp-tools#L960-L963
https://github.com/bluehost/wp-tools/blob/master/script/wp-tools#L1099-1103

**Comment by chazmcgarvey** [comment]
I am closing this issue in preparation for archiving.
