### ISSUE TITLE
Is it possible update all Wordpress site using a single command

### ISSUE THREAD

**Issue by RomanEpo** [bluehost/wp-tools#7]
Hi,
I want to update all wordpress CMS,theme and plugin using a single command.
How to to do it ?

Regards
Roman Epo

**Comment by chazmcgarvey** [comment]
Each invocation `wp-tools` can backup, restore, or upgrade one WordPress site, but `wp-tools` can easily be scripted to achieve whatever you like.

Here's a sample program that will search for WordPress sites and use `wp-tools` to upgrade each one it can find, one at a time: https://gist.github.com/6e035ced87e121c7a533 (written in Perl, but you can write stuff like this in your favorite shell script flavor or whatever you like).

**Comment by chazmcgarvey** [comment]
I am closing this issue in preparation for archiving.
